// import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
// import './globals.css';
// import Navbar from './components/Navbar/Navbar';
// import Login from './login/page';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang='en' className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
//       <body className='min-h-full flex flex-col'>
//         {/* <Login/> */}
//        <Navbar>{children}</Navbar>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import LayoutWrapper from './components/LayoutWrapper';
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <LayoutWrapper>{children}</LayoutWrapper>
<Toaster
  position="top-right"
  toastOptions={{
    duration: 3000,
    style: {
      borderRadius: '8px',
      fontSize: '14px',
    },
    error: {
      style: {
        background: '#DC2626', // Red
        color: '#fff',
      },
    },
    success: {
      style: {
        background: '#16A34A', // Green
        color: '#fff',
      },
    },
  }}
/>      </body>
    </html>
  );
}
