export const categories = [
  'Web Infographics',
  'Miscellaneous',
  'Entertainment',
  'Social Media',
  'Education',
  'Travel',
  'Technology',
  'Holiday',
  'Health',
  'Animal',
  'Love',
  'Automobile',
  'Business',
  'Food & Drink',
  'Environmental',
  'World',
  'Fashion',
  'Wedding',
  'Sports',
  'Legal',
  'Politics',
  'Internet',
  'Science',
  'Mobile',
  'History',
  'Insurance',
];
